title: Great South Bay Coffee
description: >- 
  Great South Bay Coffee's home on the Information Super Highway!
baseurl: ""
url: "https://GSBC-longisland.github.io"
remote_theme: pages-themes/tactile@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
github: [metadata]
