title: Great South Bay Coffee
description: >- 
  Great South Bay Coffee's home on the Information Super Highway!
baseurl: ""
url: "https://GSBC-longisland.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
github: [metadata]
